/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.94
 * Generated at: 2019-07-08 08:29:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"\" href=\"css/signup.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t<title>Sign Up</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"signup-div hero-image\">\r\n");
      out.write("<div style=\"text-align: center;\" ><h1>please sign up here!</h1></div>\r\n");
      out.write("<section>\r\n");
      out.write("\t<div class=\"container bg-color\">\r\n");
      out.write("\t");
 try{ 
      out.write("\r\n");
      out.write("\t\t<form action=\"Signupservlet\" enctype=\"multipart/form-data\" method=\"POST\" name=\"regF\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t  \t<div class=\"row \">\r\n");
      out.write("\t\t    <div class=\"col mid\">\r\n");
      out.write("\t\t      <label style=\"width:140px\" >name</label>\r\n");
      out.write("\t\t      <input type=\"text\" placeholder=\"enter unique username\"  name=\"name\" onblur=\"checkExist()\"required><span id=\"isE\"></span><br><br>\r\n");
      out.write("\t\t      <!-- <button class=\"btn btn-primary\" formaction=\"checkuniqservlet\" >Check</button><br> -->\r\n");
      out.write("\t\t      <label class=\"but\" style=\"width:140px\">image</label>\r\n");
      out.write("\t\t      <input type=\"file\" name=\"file\" ><br>\r\n");
      out.write("\t\t      <label style=\"width:140px\">address</label>\r\n");
      out.write("\t\t      <input type=\"text\" name=\"address\" required><br>\r\n");
      out.write("\t\t      <label style=\"width:140px\">college</label>\r\n");
      out.write("\t\t      <input type=\"text\" name=\"college\"required><br>\r\n");
      out.write("\t\t      <label style=\"width:140px\">hostel</label>\r\n");
      out.write("\t\t      <input type=\"text\" name=\"hostel\"required><br>\r\n");
      out.write("\t\t      <label style=\"width:140px\">room</label>\r\n");
      out.write("\t\t      <input type=\"text\" name=\"room\"required><br>\r\n");
      out.write("\t\t      <label style=\"width:140px\">postal</label>\r\n");
      out.write("\t\t      <input type=\"number\" name=\"postal\"required><br>\r\n");
      out.write("\t\t      <label style=\"width:140px\">phone</label>\r\n");
      out.write("\t\t      <input type=\"number\" name=\"phone\"required><br>\r\n");
      out.write("\t\t      <label style=\"width:140px\">payment-methods</label>\r\n");
      out.write("\t\t      <input type=\"text\" name=\"payment-methods\"required><br>\r\n");
      out.write("\t\t      <label style=\"width:140px\">passwords</label>\r\n");
      out.write("\t\t      <input type=\"text\" name=\"password\"required><br>\r\n");
      out.write("\t\t      <button class=\"but\" type=\"submit\" >Sign Up!</button>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    <div class=\"col mid\">\r\n");
      out.write("\t\t      <button href=\"#\" class=\"fa fa-google\" style=\"width: 200px\">Sign up with <b>Google</b></button>\r\n");
      out.write("\t\t      <p>or</p>\r\n");
      out.write("\t\t      <button href=\"#\" class=\"fa fa-facebook\" style=\"width: 200px\">Sign up with <b>Facebook</b></button>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t");
}
		catch(Exception e){
			System.out.println("lol sighup.jsp not giving error in unique cases");
			response.sendRedirect("error.jsp");
		}
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
